version: "3.8"
services:
  # PHP service
  app:
    build: .docker
    user: ${DOCKER_APP_UUID:-0}
    container_name: ${APP_CONTAINER_NAME}
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:${DB_VERSION}
    #user: ${DOCKER_DB_UUID:-0}
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:${NGINX_VERSION}
    #user: ${DOCKER_NGINX_UUID:-0}
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - ".env"
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    volumes:
      - ./:/app
      - ./.config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  composer:
    container_name: ${COMPOSER_CONTAINER_NAME}
    image: composer:${COMPOSER_VERSION}
    user: ${DOCKER_COMPOSER_UUID:-0}
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - ".env"
    ports:
      - "85:85"

networks:
  app-network:
    driver: bridge
